<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select Product-- Advance Payment G_bf3e42</name>
   <tag></tag>
   <elementGuidId>63b27005-a47d-4518-8de6-7f6a7c6d8e00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='proposedProductId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#proposedProductId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required-input ng-pristine ng-invalid ng-touched</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>proposedProductId</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>proposedProductId</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>proposedProductId</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select Product-- Advance Payment Guarantee Rivers State APRV  ADVANCE PAYMENT GUARANTEES APGT  AGRIBIZ SME INVESTMENT SCHEME ASIS  AGRI-BUSINESS SME INVESTMENT SCHEME AGIS  AGRIC CREDIT FOR AGRO-PROCESSING AGAP  AGRIC CREDIT FOR FOOD CROPS AGFC  AGRICULTURAL GROWTH ENHANCEMENT  AGES  Bank Guarantee BKGT  BID TENDER BONDS BTBD  BILLS - COMMERCIAL PAPERS (BOUGHT) TLIM  BILLS - COMMERCIAL PAPERS (BOUGHT) TLLP  CBN AGRIC CREDIT SCHEME (NORMAL) AGPL  CBN COMM. AGRIC CREDIT SCHEME CACS  CBN- ON-LENDING INTERVENTION FUND DCRR  CBN-BOI INTERVENTION FUND BOIF  CBN-EXCESS CRUDE ACCOUNT BAILOUT ECAB  CBN-POWER AND AVIATION INTVT. FUND PAIF  CHINA  PAYMENT TIME LOAN CHPF  COMMERCIAL NOTES - ASSETS CN01  CONFIRMED LETTER OF CREDIT C0LC  CORPORATE MORA PRODUCT CLMT  CORPORATE TERM LOANS AMORTIZED CTLA  CORPORATE TERM LOANS CIDA  CORPORATE TERM LOANS CIDS  CORPORATE TERM LOANS CTLM  CORPORATE TERM LOANS CTLN  CORPORATE TERM LOANS NMRT  CORPORATE TERM LOANS PFTL  CORPORATE TIME LOANS AMORTIZED CTIA  CORPORATE TIME LOANS NORMAL CTIN  Custom bonds CUBD  DB COMM. MORT. LOANS (NORMAL) DCML  DB COMM. MORT. PRODUCT (AMORTIZED) DCMP  DIAMOND CASH COLLATERAL EBCC  DIAMOND LEASE PRODUCT PROGRAM DLCC  FINANCE LEASES FL01  INDEMNITY BONDS IDMT  INSTANT BUSINESS LOAN ASSET IBL2  LEASE FIN FACILITY (BEARING) NORMAL LE03  MORTGAGE FINANCE FACILITY AMORTIZED NMRA  NIGERIA INCENTIVE BASE RISK SHARING SYSTEM  NRSA  OIL AND GAS CONTRACT FINANCE  DOGF  ON-LENDING LOAN - DUE FROM CUSTOMER ABPF  ON-LENDING LOAN - DUE FROM CUSTOMER CACA  ON-LENDING LOAN - DUE FROM CUSTOMER DBNF  ON-LENDING LOAN - DUE FROM CUSTOMER ECAR  ON-LENDING LOAN - DUE FROM CUSTOMER MSME  ON-LENDING LOAN - DUE FROM CUSTOMER OL01  ON-LENDING LOAN - DUE FROM CUSTOMER SANF  ON-LENDING LOAN - DUE FROM CUSTOMER SWSB  ON-LENDING LOAN - DUE FROM CUSTOMER SWSR  OTHER BONDS OTBD  OTHER GUARANTEE OTGT  OVERDRAFT 10001  PERFORMANCE BONDS  PFBD  REAL SECTOR SUPPORT FACILITY RSSF  RECEIVABLES - DISCOUNTING INVEST. RDPI  RECVABLE DISC INVOICE PRGM-RDIP   RDIP  RESTRUCTURED AGRIC LOANS NORMAL RALN  RETAIL TERM LOAN RTLN 0147 0147  RETAIL TIME LOAN RTIN 0148  Retention bonds RTBD  T/L - LOCAL PURCHASE ORDER FACILITY 	LTOD  T/L - LOCAL PURCHASE ORDER FACILITY LPOF  Temporary retention bonds RBLN  TERM LOANS - PAST DUE(NEW) LTP1  TRADE FINANCE LIMITS TRACKING  FALC  TRADE FINANCE LIMITS TRACKING  FALCR  TRADE TIME LOAN - IMPORT(UPFRONT)  BAIM  TRADE TIME LOAN - LOCAL(UPFRONT) BALP  UNCONFIRMED OPERATIVE LC UNLL  USANCE LETTERS OF CREDIT USLL </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;proposedProductId&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='proposedProductId']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='entry']/div/form/div/div[2]/div/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sector'])[1]/following::select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subsector'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is Fully Cash Collaterized?'])[1]/preceding::select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
   </webElementXpaths>
</WebElementEntity>
